Repository ghd-trainingfeb24/caption-this-ghd1, pull requests merged in 2024-02, with the labels that each got.

#8 Added my caption
  _slides/14-michaelwreeves.md
Labels: documentation, enhancement, good first issue

#12 added comment to 07-rol09003.md
  _slides/07-rol09003.md
Labels: documentation, enhancement

#25 Update Slide 6 omoferacho
  _slides/05-omoferacho.md
Labels: documentation

#16 Update Slide 6 persephione
  _slides/06-persephione.md
Labels: documentation
